# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://linneakirby.com"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = true
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[languages]
  [languages.en]
    languageName = 'en'
    LanguageCode = 'en-us'
    title = "linnea.club"
    [languages.en.params]
      description = "circus technologist"
      cvName = "LKirby_CV-en.pdf"
  [languages.fr]
    languageName = 'fr'
    LanguageCode = 'fr-ca'
    title = "linnea.club"
    [languages.fr.params]
        description = "technologue du cirque"
        #cvName = "LKirby_CV-fr.pdf"

[imaging]
  anchor = 'Center'

[params]
  title = "linnea.club"
  favicon = "favicon.ico"

[params.author]
  name = "Linnea Kirby"
  image = "assets/self.jpg"
  headline = "circus technologist"


[[params.externalSites]]
  name = "GitHub"
  href = "https://github.com/linneakirby"
  icon = "github.png"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
