languageCode = "en"
languageName = "English"
weight = 1
title = "linnea.club"

[params]
  displayName = "FR"
  isoCode = "fr-ca"
  rtl = false
  dateFormat = "2 January 2006"
  #cvName = "LKirby_CV-fr.pdf"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "site web de Linnéa Kirby"
  # copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "Linnéa Kirby"
   image = "self.jpg"
   headline = "personne renaissance contemporaine"
#   bio = "A little bit about you"
#   links = [
#     { email = "mailto:linnea@linneakirby.com" },
#     { link = "https://linneakirby.com/" },
#     { github = "https://github.com/linneakirby" },
#     { instagram = "https://instagram.com/kirbabby" },
#     { researchgate = "https://www.researchgate.net/profile/Linnea-Kirby" },
#   ]
