languageCode = "en"
languageName = "English"
weight = 1
title = "linnea.club"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  cvName = "LKirby_CV-en.pdf"
  # logo = "self.jpg"
  # secondaryLogo = "tileBW.png"
  # description = "Homepage of Linnéa Kirby"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
   name = "Linnéa Kirby"
   image = "self.jpg"
   headline = "circus technologist"
   # bio = "A little bit about you"
   links = [
     { email = "mailto:linnea@linneakirby.com" },
#     { link = "https://linneakirby.com/" },
     { github = "https://github.com/linneakirby" },
     { instagram = "https://instagram.com/kirbabby" },
     { researchgate = "https://www.researchgate.net/profile/Linnea-Kirby" },
   ]
